name: 'js-missing-test'
description: 'Adds comment on PR if added file has no test'
author: 'pznamir00'

inputs:
  repo:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'Number of pull request'
    required: true
  gh_token:
    description: 'The Github token for access to the repo'
    required: true

runs:
  using: node20
  main: dist/index.js
